# SPDX-FileCopyrightText: 2021-2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: CC0-1.0

version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      timezone: Europe/Paris
    open-pull-requests-limit: 10
    versioning-strategy: "increase"
    labels:
    - 3. to review
    - dependencies

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      timezone: Europe/Paris
    open-pull-requests-limit: 10
    labels:
    - 3. to review
    - dependencies
