# SPDX-FileCopyrightText: 2021-2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT

name: L10n
on: pull_request

permissions:
  contents: read

jobs:
  l10n-extract-check:
    runs-on: ubuntu-latest

    name: Pot check
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Set up node
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version-file: 'package.json'

      - name: Install dependencies
        run: npm ci

      - name: Extract l10n files
        run: npm run l10n:extract

      - name: Check l10n file changes
        run: bash -c "[[ ! \"`git status --porcelain l10n`\" ]] || ( echo 'Uncommited l10n changes. Run \`npm run l10n:extract\`.' && exit 1 )"
